core/urls.py
from django.urls import path
from.views import ItemDetailView, CheckoutView, HomeView, add_to_cart, remove_from_cart, OrderSummaryView, remove_single_item_from_cart, PaymentView, AddCouponView, RequestRefundView, PayPal, paypal_return, paypal_cancel

app_name = 'core'
urlpatterns =  [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout/', CheckoutView.as_view(), name='checkout-page'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>', ItemDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>', PaymentView.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('paypal/', PayPal, name='paypal'),
    path('paypal-return/', paypal_return, name='paypal-return'),
    path('paypal-cancel/', paypal_cancel, name='paypal-cancel'),
]

customadmin/urls.py
from django.conf import settings
from django.urls import path
from djecommerce.views import *


urlpatterns = [
    path('', admin_login, name="admin-login"),
    path('dashboard/', dashboard, name="dashboard"),
    path('addresses/', address_list, name='address_list'),
    path('addresses/add/', add_address, name='add_address'),
    path('addresses/<int:pk>/edit/', edit_address, name='edit_address'),
    path('addresses/<int:pk>/delete/', delete_address, name='delete_address'),
    path('coupons/', coupon_list, name='coupon_list'),
    path('coupons/add/', add_coupon, name='add_coupon'),
    path('coupons/<int:pk>/edit/', edit_coupon, name='edit_coupon'),
    path('coupons/<int:pk>/delete/', delete_coupon, name='delete_coupon'),
    path('items/', item_list_admin, name='item_list_admin'),
    path('items/add/', add_item, name='add_item'),
    path('items/<int:pk>/edit/', edit_item, name='edit_item'),
    path('items/<int:pk>/delete/', delete_item, name='delete_item'),
    path('orderitems/', orderitem_list, name='orderitem_list'),
    path('orderitems/add/', add_orderitem, name='add_orderitem'),
    path('orderitems/<int:pk>/edit/', edit_orderitem, name='edit_orderitem'),
    path('orderitems/<int:pk>/delete/', delete_orderitem, name='delete_orderitem'),
    path('orders/', order_list, name='order_list'),
    path('orders/add/', add_order, name='add_order'),
    path('orders/<int:pk>/edit/', edit_order, name='edit_order'),
    path('orders/<int:pk>/delete/', delete_order, name='delete_order'),
    path('payments/', payment_list, name='payment_list'),
    path('payments/add/', add_payment, name='add_payment'),
    path('payments/<int:pk>/edit/', edit_payment, name='edit_payment'),
    path('payments/<int:pk>/delete/', delete_payment, name='delete_payment'),
    path('refunds/', refund_list, name='refund_list'),
    path('refunds/add/', add_refund, name='add_refund'),
    path('refunds/<int:pk>/edit/', edit_refund, name='edit_refund'),
    path('refunds/<int:pk>/delete/', delete_refund, name='delete_refund'),
    path('paypaltransactions/', paypal_list, name='paypal_list'),
    path('paypaltransactions/add/', add_paypal, name='add_paypal'),
    path('paypaltransactions/<int:pk>/edit/', edit_paypal, name='edit_paypal'),
    path('paypaltransactions/<int:pk>/delete/', delete_paypal, name='delete_paypal'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', include('customadmin.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path ('dj-admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save


CATEGORY_CHOICES = {
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')

}

LABEL_CHOICES = {
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')


}

ADDRESS_CHOICES = {
    ('B', 'Billing'),
    ('S', 'Shipping')


}



class Item(models.Model):
    #id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    small_description = models.TextField()
    image = models.ImageField(upload_to='items')
    is_trending = models.BooleanField(default=False)


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:product-page", kwargs = {
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs = {
            'slug': self.slug
        })
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs = {
            'slug': self.slug
        })


#As soon as item is added to cart, becomes an order item
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete = models.CASCADE)
    ordered = models.BooleanField(default=False)
    #id = models.BigAutoField(primary_key=True)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    

class Order(models.Model):
    #id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete = models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)



    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed Checkout)
    3. Payment
    (Preprocessing, processing, packaging etc)
    4. Being delivered
    5. Received
    6. Refunds

    '''
    

    def __str__(self):
        return self.user.username
    
    """
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        total -= self.coupon.amount
        return total
        """
    
    def get_total(self):
        total = sum(item.get_final_price() for item in self.items.all())
        if self.coupon:
            total -= self.coupon.amount
        return total



class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete = models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, blank=True, null=True)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = 'Addresses'
        
    
class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code
    

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

# models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class PayPalTransaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(_('Transaction ID'), max_length=255)
    amount = models.DecimalField(_('Amount'), max_digits=10, decimal_places=2)
    status = models.CharField(_('Status'), max_length=20)
    timestamp = models.DateTimeField(_('Timestamp'), auto_now_add=True)

    class Meta:
        verbose_name = _('PayPal Transaction')
        verbose_name_plural = _('PayPal Transactions')

    def __str__(self):
        return f"{self.user.username} - {self.transaction_id}"

customadmin/models.py
from django.db import models

# Create your models here.

customadmin/forms.py
from django import forms
from core.models import Address, Coupon, Item, OrderItem, Order, Payment, Refund, PayPalTransaction

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['street_address', 'apartment_address', 'country', 'zip', 'address_type', 'default']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(AddressForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(AddressForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance



class CouponListForm(forms.ModelForm):
    class Meta:
        model = Coupon
        fields = ['code', 'amount']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(CouponListForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(CouponListForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance
    
class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['title', 'price', 'discount_price', 
                  'category', 'label', 'slug', 
                  'description', 'small_description', 'image', 'is_trending']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ItemForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(ItemForm, self).save(commit=False)
        instance.user = self.user  
        if commit:
            instance.save()
        return instance
    

class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['user', 'ordered', 'item', 'quantity']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(OrderItemForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(OrderItemForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance
    
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'ref_code', 'items', 'ordered_date', 'ordered',
                  'shipping_address', 'billing_address', 'payment',
                  'coupon', 'being_delivered', 'received',
                  'refund_requested', 'refund_granted']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(OrderForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(OrderForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance
    
class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['stripe_charge_id', 'user', 'amount']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(PaymentForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(PaymentForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance
    

class RefundForm(forms.ModelForm):
    class Meta:
        model = Refund
        fields = ['order', 'reason', 'accepted', 'email']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(RefundForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(RefundForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance
    
class PaypalForm(forms.ModelForm):
    class Meta:
        model = PayPalTransaction
        fields = ['user', 'transaction_id', 'amount', 'status']

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(PaypalForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(PaypalForm, self).save(commit=False)
        instance.user = self.user  # Set the user for the address
        if commit:
            instance.save()
        return instance

customadmin/templates/address_form.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Add/Edit Address{% endblock %}

{% block content %}
<div class="container mt-5 pt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="main-content">
                <h2>Add/Edit Address</h2>
                <form method="post" class="address-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save Address</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

customadmin/templates/address_list.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Address List{% endblock %}

{% block content %}
<!-- Main content -->
<div class="container mt-5 pt-4">
    <div class="row">
        <div class="col-md-12">
            <div class="main-content">
                <h2>Address List</h2>
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Street Address</th>
                            <th>Apartment Address</th>
                            <th>Country</th>
                            <th>ZIP Code</th>
                            <th>Address Type</th>
                            <th>Default</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for address in addresses %}
                        <tr>
                            <td>{{ address.street_address }}</td>
                            <td>{{ address.apartment_address }}</td>
                            <td>{{ address.country }}</td>
                            <td>{{ address.zip }}</td>
                            <td>{{ address.get_address_type_display }}</td>
                            <td>{% if address.default %} Yes {% else %} No {% endif %}</td>
                            <td>
                                <a href="{% url 'edit_address' address.pk %}" class="btn btn-success btn-sm edit-btn">Edit</a>
                                <a href="{% url 'delete_address' address.pk %}" class="btn btn-danger btn-sm delete-btn">Delete</a>
                            </td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td colspan="7">No addresses found.</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!-- Add Address Button -->
<div class="float-right">
    <a href="{% url 'add_address' %}" class="btn btn-primary btn-sm">
        <i class="fas fa-plus"></i> Add Address
    </a>
    {% endblock %}

</div>

customadmin/templates/addresses.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Add/Edit Address</title>
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    
    <!-- Inline style specific to this page -->
    <style type="text/css">
        html,
        body,
        .admin-dashboard {
            height: 100%;
        }
        
        body {
            display: flex;
            flex-direction: column;
            background-color: #f5f5f5; /* Adjust background color as needed */
        }
        
        .admin-dashboard {
            display: flex;
            flex: 1;
            flex-direction: column;
        }
        
        .main-content {
            flex: 1;
            padding: 20px;
        }
        
        /* Form style */
        .address-form {
            background-color: #ffffff;
            padding: 20px;
            margin-top: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        
        .form-group {
            margin-bottom: 20px;
        }
        
        label {
            font-weight: bold;
        }
        
        input[type="text"], select {
            width: 100%;
            padding: 8px;
            border: 1px solid #ccc;
            border-radius: 4px;
            box-sizing: border-box;
            font-size: 16px;
        }
        
        button[type="submit"] {
            background-color: #007bff;
            color: white;
            border: none;
            padding: 10px 20px;
            cursor: pointer;
            border-radius: 4px;
        }
        
        button[type="submit"]:hover {
            background-color: #0056b3;
        }
        
        /* Table styles */
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        
        th {
            background-color: #f2f2f2;
        }
        
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>

<!-- Navbar -->
<nav class="navbar fixed-top navbar-expand-lg navbar-light">
    <div class="container">
        <a class="navbar-brand" href="#">Admin Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 1</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 2</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 3</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link 4</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- /.Navbar -->

<!-- Main content -->
<div class="admin-dashboard">
    <div class="container mt-5 pt-4">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="main-content">
                    <!-- Address Form -->
                    <div class="address-form">
                        <h2>Add/Edit Address</h2>
                        <form method="post" class="mb-4">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Save Address</button>
                        </form>
                    </div>
                    
                    <!-- Address List -->
                    <div class="address-list">
                        <h2>Address List</h2>
                        <table>
                            <thead>
                                <tr>
                                    <th>Street Address</th>
                                    <th>Apartment Address</th>
                                    <th>Country</th>
                                    <th>ZIP Code</th>
                                    <th>Address Type</th>
                                    <th>Default</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for address in addresses %}
                                    <tr>
                                        <td>{{ address.street_address }}</td>
                                        <td>{{ address.apartment_address }}</td>
                                        <td>{{ address.country }}</td>
                                        <td>{{ address.zip }}</td>
                                        <td>{{ address.get_address_type_display }}</td>
                                        <td>{% if address.default %} Yes {% else %} No {% endif %}</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="6">No addresses found.</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.Main content -->

<!-- Footer -->
<footer class="page-footer">
    <div class="container-fluid">
        <ul class="list-unstyled list-inline">
            <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
            </li>
            <li class="list-inline-item">
                <a href="#">Terms and Conditions</a>
            </li>
            <li class="list-inline-item">
                <a href="#">FAQ</a>
            </li>
        </ul>
    </div>
</footer>
<!-- /.Footer -->

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>

</body>
</html>

customadmin/templates/coupon_form.html
{% extends 'dashboard.html' %}
{% load static %}

{% block title %}Add/Edit Coupon{% endblock %}

{% block content %}
<div class="container mt-5 pt-4">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="main-content">
                <h2>Add/Edit Coupon</h2>
                <form method="post" class="coupon-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Save Coupon</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

customadmin/templates/item_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Item</title>
    <!-- Include Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <h2>Edit Item</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Update Item</button>
        </form>
    </div>
    <!-- Include Bootstrap JS and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>
</html>

customadmin/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Login</title>
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    
    <!-- Custom styles -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    
    <!-- Inline style specific to this page -->
    <style type="text/css">
        html,
        body {
            height: 100%;
        }
        
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            background-color: #f5f5f5; /* Adjust background color as needed */
        }
        
        .card {
            width: 100%;
            max-width: 400px; /* Limit card width for better readability */
            padding: 20px;
            border: 1px solid rgba(0, 0, 0, 0.125); /* Add border for visual separation */
            border-radius: 5px;
            background-color: #ffffff; /* Card background color */
            box-shadow: 0 0 15px rgba(0, 0, 0, 0.1); /* Add shadow for depth */
        }
        
        .card-header {
            background-color: #007bff; /* Header background color */
            color: #ffffff; /* Header text color */
            text-align: center; /* Center align header text */
            padding: 10px 0; /* Add padding to header */
            border-radius: 5px 5px 0 0; /* Rounded corners only at the top */
        }
        
        .card-body {
            padding: 15px; /* Add padding inside card body */
        }
        
        .form-group {
            margin-bottom: 20px; /* Adjust margin between form elements */
        }
    </style>
</head>
<body>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h2>Login</h2>
                </div>
                <div class="card-body">
                    {% if messages %}
                        {% for message in messages %}
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                {{ message }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">Username</label>
                            <input type="text" class="form-control" id="id_username" name="username" required autofocus>
                        </div>
                        <div class="form-group">
                            <label for="id_password">Password</label>
                            <input type="password" class="form-control" id="id_password" name="password" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- SCRIPTS -->
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
<!-- Initializations -->
<script type="text/javascript">
    // Animations initialization
    new WOW().init();
</script>

</body>
</html>