core/urls.py
from django.urls import path
from.views import ItemDetailView, CheckoutView, HomeView, add_to_cart, remove_from_cart, OrderSummaryView, remove_single_item_from_cart, PaymentView, AddCouponView, RequestRefundView, PayPal, paypal_return, paypal_cancel

app_name = 'core'
urlpatterns =  [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout/', CheckoutView.as_view(), name='checkout-page'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>', ItemDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>', PaymentView.as_view(), name='payment'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('paypal/', PayPal, name='paypal'),
    path('paypal-return/', paypal_return, name='paypal-return'),
    path('paypal-cancel/', paypal_cancel, name='paypal-cancel'),
]

djecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', include('customadmin.urls')),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path ('dj-admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
from django.db.models.signals import post_save


CATEGORY_CHOICES = {
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')

}

LABEL_CHOICES = {
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')


}

ADDRESS_CHOICES = {
    ('B', 'Billing'),
    ('S', 'Shipping')


}



class Item(models.Model):
    #id = models.BigAutoField(primary_key=True)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    small_description = models.TextField()
    image = models.ImageField(upload_to='items')
    is_trending = models.BooleanField(default=False)


    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:product-page", kwargs = {
            'slug': self.slug
        })
    
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs = {
            'slug': self.slug
        })
    
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs = {
            'slug': self.slug
        })


#As soon as item is added to cart, becomes an order item
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete = models.CASCADE)
    ordered = models.BooleanField(default=False)
    #id = models.BigAutoField(primary_key=True)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()
    
    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    

class Order(models.Model):
    #id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete = models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey('Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey('Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey('Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey('Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)



    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed Checkout)
    3. Payment
    (Preprocessing, processing, packaging etc)
    4. Being delivered
    5. Received
    6. Refunds

    '''
    

    def __str__(self):
        return self.user.username
    
    """
    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        total -= self.coupon.amount
        return total
        """
    
    def get_total(self):
        total = sum(item.get_final_price() for item in self.items.all())
        if self.coupon:
            total -= self.coupon.amount
        return total



class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             on_delete = models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100, blank=True, null=True)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
    class Meta:
        verbose_name_plural = 'Addresses'
        
    
class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username
    

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code
    

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

# models.py

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _

class PayPalTransaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    transaction_id = models.CharField(_('Transaction ID'), max_length=255)
    amount = models.DecimalField(_('Amount'), max_digits=10, decimal_places=2)
    status = models.CharField(_('Status'), max_length=20)
    timestamp = models.DateTimeField(_('Timestamp'), auto_now_add=True)

    class Meta:
        verbose_name = _('PayPal Transaction')
        verbose_name_plural = _('PayPal Transactions')

    def __str__(self):
        return f"{self.user.username} - {self.transaction_id}"

core/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)

class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label="(Select a Country)").formfield(required=False,
    widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100',
        'id': 'zip'
    }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label="(Select a Country)").formfield(required=False,
    widget=CountrySelectWidget(attrs={
        'class': 'custom-select d-block w-100',
        'id': 'zip'
    }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing= forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES)



class CouponForm(forms.Form):
    code = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Promo Code',
        'aria-label': 'Recipient\\s username',
        'aria-describedby': 'basic-addon2'
    }))

class RefundForm(forms.Form):
    ref_code = forms.CharField()
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 4
    }))
    email = forms.EmailField()






class PaymentForm(forms.Form):
    stripeToken = forms.CharField(max_length=500, required=True, widget=forms.HiddenInput())
    save_card_info = forms.BooleanField(label='Save card information for future use', required=False)
    card_last_4 = forms.CharField(max_length=4, required=False, widget=forms.HiddenInput(attrs={'id': 'card-last-4'}))
    card_expiry = forms.CharField(max_length=5, required=False, widget=forms.HiddenInput(attrs={'id': 'card-expiry'}))

core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Ecommerce</title>
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
    <style type="text/css">
        html,
        body,
        header,
        .carousel {
            height: 60vh;
        }

        @media (max-width: 740px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }

        @media (min-width: 800px) and (max-width: 850px) {

            html,
            body,
            header,
            .carousel {
                height: 100vh;
            }
        }
    </style>
</head>

<body>

    <div class="mt-5 pt-4">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
            </button>
        </div>
        {% endfor %}
        {% endif %}
    </div>

    <script>
        // Function to close the alert message after 10 seconds
        setTimeout(function () {
            $('.alert').alert('close');
        }, 10000); // 10000 milliseconds = 10 seconds
    </script>

    {% load cart_template_tags %}

    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
        <div class="container">

            <!-- Brand -->
            <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
                <strong class="blue-text">E-commerce</strong>
            </a>

            <!-- Collapse -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <!-- Left -->
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link waves-effect" href="/">Home
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <!--   <li class="nav-item">
                        <a class="nav-link waves-effect" href="/checkout/">Checkout</a>
                    </li>
                    -->
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'core:request-refund' %}">Refund Request</a>
                    </li>


                    <!-- 
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="https://mdbootstrap.com/education/bootstrap/"
                            target="_blank">Free
                            tutorials</a>  -->
                    </li>
                </ul>

                <!-- Right -->
                <ul class="navbar-nav nav-flex-icons">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
                            <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
                            <i class="fas fa-shopping-cart"></i>
                            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Logout </span>
                        </a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'account_login' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Login </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
                            <span class="clearfix d-none d-sm-inline-block"> Signup </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://www.facebook.com/mdbootstrap" class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-facebook-f"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://twitter.com/MDBootstrap" class="nav-link waves-effect" target="_blank">
                            <i class="fab fa-twitter"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/mdbootstrap/bootstrap-material-design"
                            class="nav-link border border-light rounded waves-effect" target="_blank">
                            <i class="fab fa-github mr-2"></i>MDB GitHub
                        </a>
                    </li>
                    {% endif %}
                </ul>

            </div>

        </div>
    </nav>
    <!-- Navbar -->



    <!--Carousel Wrapper-->
    <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

        <!--Indicators-->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-1z" data-slide-to="1"></li>
            <li data-target="#carousel-example-1z" data-slide-to="2"></li>
        </ol>
        <!--/.Indicators-->

        {% block content %}
        {% endblock content %}

        {% block extra_body %}
        {% endblock %}

    </div>
    <!--Carousel Wrapper-->

    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">



        <hr class="my-4">

        <!-- Social icons -->
        <div class="pb-4">
            <a href="https://www.facebook.com/mdbootstrap" target="_blank">
                <i class="fab fa-facebook-f mr-3"></i>
            </a>

            <a href="https://twitter.com/MDBootstrap" target="_blank">
                <i class="fab fa-twitter mr-3"></i>
            </a>

            <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
                <i class="fab fa-youtube mr-3"></i>
            </a>

            <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
                <i class="fab fa-google-plus-g mr-3"></i>
            </a>

            <a href="https://dribbble.com/mdbootstrap" target="_blank">
                <i class="fab fa-dribbble mr-3"></i>
            </a>

            <a href="https://pinterest.com/mdbootstrap" target="_blank">
                <i class="fab fa-pinterest mr-3"></i>
            </a>

            <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
                <i class="fab fa-github mr-3"></i>
            </a>

            <a href="http://codepen.io/mdbootstrap/" target="_blank">
                <i class="fab fa-codepen mr-3"></i>
            </a>
        </div>
        <!-- Social icons -->

        <!--Footer Links-->
        <div class="container-fluid">
            <ul class="list-unstyled list-inline">
                <li class="list-inline-item">
                    <a href="https://mdbootstrap.com/docs/jquery/about/privacy-policy/" target="_blank">Privacy
                        Policy</a>
                </li>
                <li class="list-inline-item">
                    <a href="https://mdbootstrap.com/docs/jquery/about/terms-conditions/" target="_blank">Terms and
                        Conditions</a>
                </li>
                <li class="list-inline-item">
                    <a href="https://mdbootstrap.com/docs/jquery/faq/" target="_blank">FAQ</a>
                </li>
            </ul>
        </div>
        <!--Footer Links-->

        <hr class="my-4">

        <div class="pb-4">
            <a href="https://mdbootstrap.com/discount/offer/" target="_blank">
                <img src="https://mdbootstrap.com/img/Marketing/campaign-1.jpg" alt="" class="img-fluid">
            </a>
        </div>

    </footer>
    <!--/.Footer-->

    <!-- SCRIPTS -->
    <!-- JQuery -->
    <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
    <!-- Initializations -->
    <script type="text/javascript">
        // Animations initialization
        new WOW().init();
    </script>

    <script>
        // MDB Lightbox Init
        $(function () {
            $("#mdb-lightbox-ui").load("mdb-addons/mdb-lightbox-ui.html");
        });
    </script>
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>

</html>

core/templates/home-page.html
{% extends 'base.html' %}
{% block content %}

<body>
  <!--Slides-->
  <div class="carousel-inner" role="listbox">

    <!--First slide-->
    <div class="carousel-item active">
      <div class="view"
        style="background-image: url('/static/img/img_first.jpeg'); background-repeat: no-repeat; background-size: cover;">


        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Unlock Your Online Potential</strong>
            </h1>

            <p>
              <strong>Empower Your Business with Our Ecommerce Platform</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Take your business to new heights with our comprehensive ecommerce solution. From building your
                online store to managing orders and reaching customers, we provide the tools and support you need to
                succeed. Join thousands of successful online businesses and start selling today!</strong>
            </p>


          </div>
          <!-- Content -->

        </div>
        <!-- Mask & flexbox options-->

      </div>
    </div>
    <!--/First slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div class="view"
        style="background-image: url('/static/img/img_second.jpeg'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Discover Your Online Potential</strong>
            </h1>

            <p>
              <strong>Transform Your Business with Our Ecommerce Platform</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Elevate your online presence and boost your sales. Our powerful ecommerce solution offers
                everything you need to launch, manage, and expand your online store. With user-friendly features and
                expert support, achieving your online goals has never been easier.</strong>
            </p>
          </div>
        </div>
      </div>
    </div>

    <!--/Second slide-->

    <!--Third slide-->
    <div class="carousel-item">
      <div class="view"
        style="background-image: url('/static/img/img_third.jpeg'); background-repeat: no-repeat; background-size: cover;">

        <!-- Mask & flexbox options-->
        <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

          <!-- Content -->
          <div class="text-center white-text mx-5 wow fadeIn">
            <h1 class="mb-4">
              <strong>Your Ultimate Ecommerce Solution</strong>
            </h1>

            <p>
              <strong>Unleash Your Online Potential</strong>
            </p>

            <p class="mb-4 d-none d-md-block">
              <strong>Empower your business with our intuitive ecommerce platform. Seamlessly create, manage, and grow
                your online store with ease. Join thousands of successful entrepreneurs who trust our platform to drive
                their online success.</strong>
            </p>
          </div>
        </div>
      </div>
    </div>

    <!-- Content -->

  </div>
  <!-- Mask & flexbox options-->

  </div>
  </div>
  <!--/Third slide-->

  </div>
  <!--/.Slides-->

  <!--Controls-->
  <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  <!--/.Controls-->

  </div>
  <!--/.Carousel Wrapper-->

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->


          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="?category=S">Shirts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="?category=SW">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="?category=OW">Outwears</a>
            </li>
          </ul>
          <!-- Links -->

          <form class="form-inline" method="GET" action="/">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" name="q" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-white btn-md my-0 ml-sm-2" type="submit">Search</button>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">
          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="/static/img/12.jpeg" class="card-img-top" alt=""> -->
                <img src="{{item.image.url}}" class="card-img-top" alt="">
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      <span class="badge badge-pill {{ item.get_label_display}}-color">NEW</span>
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}
        </div>



      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--First
          <li class="page-item disabled">
            <a class="page-link" tabindex="-1">First</a>
          </li>
-->
          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
          </li>
          {% endif %}

          <!--Numbers-->
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}"></a>
          </li>


          {% if page_obj.has_next %}
          <!--Arrow right-->
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
          </li>
          {% endif %}

          <!--Last
          <li class="page-item">
            <a class="page-link">Last</a>
          </li> -->
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>
  <!--Main layout-->
</body>

{% endblock %}

core/templates/item_list.html
{% extends 'base.html'%}

{% block content%}
<h2>Here is the list of items</h2>

{% for item in items%}
{{item}}
{% endfor %}
{% endblock content %}

core/templates/paypal.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="payment-box">
        <h1>Pay with PayPal</h1>
       <p><strong>Amount to be paid:</strong> ${{ form.amount.value|floatformat:"2" }}</p>

        <div id="form-container">
            {{ form.render}}
        </div>
        <img alt="" width="1" height="1" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif">
    </div>
</div>
{% endblock %}

core/templates/request_refund.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


<main>
    <div class="container">
        <div class="table-responsive">
            <h2>Request Refund </h2>
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class=" btn btn-primary"> Submit </button>
            </form>

        </div>

    </div>

</main>
{% endblock %}